### PR TITLE
Implement end of call stack on x86_64/loongarch64 (correctly?)

### PR DESCRIPTION
**Pull request by jellllly420**
Thanks to @lrh2000 for noticing [bugs](https://github.com/asterinas/asterinas/pull/2383#discussion_r2306882059) introduced in #2383. This PR reverts the changes about the bug and implement end-of-stack mechanism for x86_64/loongarch64 just like I did for riscv64 in #2383.

The x86_64 change is tested. I still don't know why CI didn't complain about #2383 but I believe the changes here is correct.

The loongarch64 change is not tested because I don't know how to boot up a loongarch64 Asterinas (at least `make run OSDK_TARGET_ARCH=loongarch64` doesn't work). However I checked the .eh_frame section of the final ELF and found that r1 register is correctly undefined there. I believe this is just what we want.
```
root@flexusx-60bc:~/asterinas# objdump -t target/osdk/aster-nix/aster-nix-osdk-bin.qemu_elf | grep kernel_task_entry_wrapper
90000000801cb4e4 g       .text  0000000000000000 kernel_task_entry_wrapper
root@flexusx-60bc:~/asterinas# objdump --dwarf=frames target/osdk/aster-nix/aster-nix-osdk-bin.qemu_elf | grep 801cb4e4 -A 5 
0001a038 00000010 0001a03c FDE cie=00000000 pc=801cb4e4..801cb4e8
  DW_CFA_undefined: r1
  DW_CFA_nop

0001a04c 00000014 0001a050 FDE cie=00000000 pc=801cb500..801cb634
  DW_CFA_advance_loc: 4 to 801cb504
``

### CODE REVIEW

**Comment by lrh2000** [comment]
> The loongarch64 change is not tested because I don't know how to boot up a loongarch64 Asterinas (at least `make run OSDK_TARGET_ARCH=loongarch64` doesn't work).

Hmm... I suspect it's broken due to this: https://github.com/asterinas/asterinas/pull/2331 (which upgrades the QEMU version).

File: ostd/src/arch/loongarch/task/switch.S [hunk 1]
```diff
@@ -35,3 +36,9 @@ first_context_switch: # (nxt: *const TaskContext)
   ld.d  $s8, $a0, 0x50
   ld.d  $ra, $a0, 0x58 # return address
   ret
+
+kernel_task_entry_wrapper:
+  .cfi_startproc
+  .cfi_undefined 1
```
Comment (lrh2000) [inline ostd/src/arch/loongarch/task/switch.S]: So this should have similar comments as the other two architectures, right?

File: ostd/src/arch/x86/task/switch.S [hunk 2]
```diff
@@ -31,8 +32,12 @@ first_context_switch: # (nxt: *const TaskContext)
...
-  mov qword ptr [rsp + 8], 0 # kernel_task_entry's return address
-  mov [rsp], rax             # first_context_switch's return address
+  mov rax, [rdi + 56] # restore return address
+  mov [rsp], rax # for stack balance, must use mov instead of push
   ret
+
+kernel_task_entry_wrapper:
+  .cfi_startproc
+  .cfi_undefined rip # mark return address as undefined to indicate end of call stack
+  jmp kernel_task_entry # use jmp to avoid side effections on stack of call
```
Comment (lrh2000) [inline ostd/src/arch/x86/task/switch.S]: Are you sure using `jmp` here will work correctly? How will the unwinding routine know the caller function if we don't push the return address?

File: ostd/src/task/mod.rs [hunk 3]
```diff
@@ -191,17 +191,13 @@ impl TaskOptions {
             scheduler::exit_current();
         }
 
-        #[cfg(target_arch = "riscv64")]
         extern "C" {
             fn kernel_task_entry_wrapper();
         }
```
Comment (lrh2000) [inline ostd/src/task/mod.rs]: Maybe move this to `ostd/src/arch/*/task/mod.rs`..?

https://github.com/asterinas/asterinas/blob/d84ad988d4a9fa5ae7bb68b6250bcfa8c34dbf56/ostd/src/arch/x86/task/mod.rs#L65-L68

File: osdk/src/base_crate/riscv64.ld.template [hunk 4]
```diff
@@ -34,6 +34,11 @@ SECTIONS
         *(.rodata .rodata.*)
     }
 
+    # Rust's "riscv64imac-unknown-none-elf" doesn't enable generation of the
+    # .eh_frame_hdr section so we don't have to declare that in linker script.
```
Comment (lrh2000) [inline osdk/src/base_crate/riscv64.ld.template]:
```suggestion
    # Rust's "riscv64imac-unknown-none-elf" target doesn't enable generation of
    # the .eh_frame_hdr section so we don't declare that in the linker script.
```

File: Makefile [hunk 5]
```diff
@@ -83,7 +83,11 @@ CARGO_OSDK_COMMON_ARGS += --profile release-lto
 OSTD_TASK_STACK_SIZE_IN_PAGES = 8
 else ifeq ($(RELEASE), 1)
 CARGO_OSDK_COMMON_ARGS += --release
-OSTD_TASK_STACK_SIZE_IN_PAGES = 16
+	ifeq ($(OSDK_TARGET_ARCH), riscv64)
+	OSTD_TASK_STACK_SIZE_IN_PAGES = 16
+	else
+	OSTD_TASK_STACK_SIZE_IN_PAGES = 8
+	endif
```
Comment (lrh2000) [inline Makefile:93]: Add a FIXME here:
```bash
# FIXME: Unwinding in RISC-V seems to cost more stack space, so we increase the
# stack size for it. This may need further investigation.
# See https://github.com/asterinas/asterinas/pull/2383#discussion_r2307673156
```

See also https://github.com/asterinas/asterinas/pull/2383#discussion_r2308978212.

**Review by lrh2000 — COMMENTED** [review]
Thanks for quickly fixing the bugs. This is a soundness issue, so this PR should be merged as soon as possible. Nevertheless, I hope the following issues can be addressed.

File: ostd/src/arch/x86/task/switch.S (hunk 2 above)
Comment (jellllly420) [reply ostd/src/arch/x86/task/switch.S]: Sorry but I'm afraid that was another mistake I made.

Now it's like this for stack balance
```
add rsp, 8
call kernel_task_entry
```

File: ostd/src/arch/loongarch/task/switch.S [hunk 6]
```diff
@@ -35,3 +36,9 @@ first_context_switch: # (nxt: *const TaskContext)
   ld.d  $s8, $a0, 0x50
   ld.d  $ra, $a0, 0x58 # return address
   ret
+
+kernel_task_entry_wrapper:
+  .cfi_startproc
+  .cfi_undefined 1 # mark return address as undefined to indicate end of call stack
+  bl kernel_task_entry
```
[the remark this answers is not in the document]
Comment (jellllly420) [reply ostd/src/arch/loongarch/task/switch.S:43]: No it acts just like RISC-V's call which stores the return address in r1 register instead of pushing that to the stack.
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html#_bl

File: ostd/src/arch/loongarch/task/switch.S [hunk 7]
```diff
@@ -35,3 +36,9 @@ first_context_switch: # (nxt: *const TaskContext)
   ld.d  $s8, $a0, 0x50
   ld.d  $ra, $a0, 0x58 # return address
   ret
+
+kernel_task_entry_wrapper:
+  .cfi_startproc
+  .cfi_undefined 1 # mark return address as undefined to indicate end of call stack
```
[the remark this answers is not in the document]
Comment (jellllly420) [reply ostd/src/arch/loongarch/task/switch.S:42]: I'd prefer consistency across different architectures.

**Review by lrh2000 — APPROVED** [review]
LGTM. Thanks for fixing the bug so quickly!

**Review by junyang-zh — APPROVED** [review]
LGTM. Sorry that I was being too hasty last time at #2383 . Hope it works this time.
